# Generated by Django 2.1.3 on 2018-11-19 17:35

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('full_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='full name')),
                ('role', models.CharField(default='Translator', max_length=220, verbose_name='Роль')),
                ('agency_id', models.IntegerField(blank=True, null=True, verbose_name='ID агенства')),
                ('last_active', models.DateTimeField(auto_now_add=True, verbose_name='last active')),
                ('is_parthner', models.BooleanField(default=False, verbose_name='parthner status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('last_active',),
            },
            managers=[
                ('objects', api.models.UserAccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Female',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=220, verbose_name='Charming login')),
                ('site_password', models.CharField(max_length=220, verbose_name='Charming password')),
                ('end_activation', models.DateTimeField(blank=True, null=True)),
                ('end_mailactivation', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.CharField(blank=True, max_length=220, null=True, verbose_name='Last visit')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Translator')),
            ],
            options={
                'ordering': ('last_update',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woman_id', models.CharField(blank=True, max_length=220, null=True)),
                ('man_id', models.CharField(blank=True, max_length=220, null=True)),
                ('message_id', models.CharField(blank=True, max_length=220, null=True)),
                ('last_update', models.CharField(blank=True, max_length=220, null=True)),
                ('text', models.TextField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Female', verbose_name='Translator')),
            ],
            options={
                'ordering': ('last_update',),
            },
        ),
    ]
